#This is the 'theme' _config.yml file
menu:
  Home:
  Archives: archives
  About: about

widgets:
- search
- category
- tag
- tagcloud
- recent_posts
- profile

socials:
- name: Github
  link: https://github.com/lane128
  icon: icon/github.png
- name: Twitter
  link: https://twitter.com/Castiel_Lane
  icon: icon/twitter.png
- name: Weibo
  link: http://weibo.com/u/2129960911
  icon: icon/weibo.png

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light

# Put your file or dir into `hexo-site/source/` directory.
favicon: /icon/favicon.png
#github_icon: /icon/github.png
#twitter_icon: /icon/twitter.png
#weibo_icon: /icon/weibo.png